parameters:
    database_host: ec2-54-235-221-102.compute-1.amazonaws.com
    database_port: '5432'
    database_name: d1b1hng8b1b9r8
    database_user: omyfsvelyuuvwq
    database_password: Mz-Ap8pZS7MLjdzHrSpxjtlTeq
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt