# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    dao.albums:
        class: AppBundle\Service\Dao\Albums
        arguments: ['@doctrine.orm.default_entity_manager']
    dao.photos:
        class: AppBundle\Service\Dao\Photos
        arguments: ['@doctrine.orm.default_entity_manager']
