# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

#services:
#    default_controller:
#        class: AppBundle\Controller\DefaultController
#        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Album')", "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Photo')", "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"]
#